### ISSUE TITLE
u8g 'menu'example port to u8g2 need help

### ISSUE THREAD

**Issue by snapedumbledore** [olikraus/u8g2#395]
u8g2 haven't 'U8GLIB_ST7920_128X64_1X(sck, mosi, cs [, reset])'  ;     I use 
‘U8G2_ST7920_128X64_1_SW_SPI(rotation, clock, data, cs [, reset]) | page buffer, size = 128 bytes ；
U8G2_ST7920_128X64_2_SW_SPI(rotation, clock, data, cs [, reset]) | page buffer, size = 256 bytes ；
U8G2_ST7920_128X64_F_SW_SPI(rotation, clock, data, cs [, reset]) ‘
instead 。but no one display correctly. What should i do ,thanks.

**Comment by olikraus** [comment]
> What should i do 

send code, send pictures, send more information

**Comment by snapedumbledore** [comment]
when i use u8glib,display correct:
![img_20171018_195202](https://user-images.githubusercontent.com/29865320/31717601-3a57d8c2-b43f-11e7-83ca-e639bed30bc0.jpg)
when use u8g2lib ,like that:
![img_20171018_195836](https://user-images.githubusercontent.com/29865320/31717615-48632368-b43f-11e7-860e-e6be7711186b.jpg)
///////////////////////////////////u8g/////////////////////////////////
#include "U8glib.h"

U8GLIB_ST7920_128X64_4X u8g(8, 9, 10);	// SPI Com: SCK = en = 18, MOSI = rw = 16, CS = di = 17

#define KEY_NONE 0
#define KEY_PREV 1
#define KEY_NEXT 2
#define KEY_SELECT 3
#define KEY_BACK 4

// DOGS102 shield configuration values
//uint8_t uiKeyPrev = 2;
//uint8_t uiKeyNext = 4;
//uint8_t uiKeySelect = 5;
//uint8_t uiKeyBack = 3;

// DOGM128-Shield	 configuration values
// DOGXL60-Shield configuration values
uint8_t uiKeyPrev = 7;
uint8_t uiKeyNext = 3;
uint8_t uiKeySelect = 2;
uint8_t uiKeyBack = 8;

uint8_t uiKeyCodeFirst = KEY_NONE;
uint8_t uiKeyCodeSecond = KEY_NONE;
uint8_t uiKeyCode = KEY_NONE;


void uiSetup(void) {
  // configure input keys 
  
  pinMode(uiKeyPrev, INPUT_PULLUP);           // set pin to input with pullup
  pinMode(uiKeyNext, INPUT_PULLUP);           // set pin to input with pullup
  pinMode(uiKeySelect, INPUT_PULLUP);           // set pin to input with pullup
  pinMode(uiKeyBack, INPUT_PULLUP);           // set pin to input with pullup
}

void uiStep(void) {
  uiKeyCodeSecond = uiKeyCodeFirst;
  if ( digitalRead(uiKeyPrev) == LOW )
    uiKeyCodeFirst = KEY_PREV;
  else if ( digitalRead(uiKeyNext) == LOW )
    uiKeyCodeFirst = KEY_NEXT;
  else if ( digitalRead(uiKeySelect) == LOW )
    uiKeyCodeFirst = KEY_SELECT;
  else if ( digitalRead(uiKeyBack) == LOW )
    uiKeyCodeFirst = KEY_BACK;
  else 
    uiKeyCodeFirst = KEY_NONE;
  
  if ( uiKeyCodeSecond == uiKeyCodeFirst )
    uiKeyCode = uiKeyCodeFirst;
  else
    uiKeyCode = KEY_NONE;
}


#define MENU_ITEMS 4
const char *menu_strings[MENU_ITEMS] = { "First Line", "Second Item", "3333333", "abcdefg" };

uint8_t menu_current = 0;
uint8_t menu_redraw_required = 0;
uint8_t last_key_code = KEY_NONE;


void drawMenu(void) {
  uint8_t i, h;
  u8g_uint_t w, d;

  u8g.setFont(u8g_font_6x13);
  u8g.setFontRefHeightText();
  u8g.setFontPosTop();
  
  h = u8g.getFontAscent()-u8g.getFontDescent();
  w = u8g.getWidth();
  for( i = 0; i < MENU_ITEMS; i++ ) {
    d = (w-u8g.getStrWidth(menu_strings[i]))/2;
    u8g.setDefaultForegroundColor();
    if ( i == menu_current ) {
      u8g.drawBox(0, i*h+1, w, h);
      u8g.setDefaultBackgroundColor();
    }
    u8g.drawStr(d, i*h, menu_strings[i]);
  }
}

void updateMenu(void) {
  if ( uiKeyCode != KEY_NONE && last_key_code == uiKeyCode ) {
    return;
  }
  last_key_code = uiKeyCode;
  
  switch ( uiKeyCode ) {
    case KEY_NEXT:
      menu_current++;
      if ( menu_current >= MENU_ITEMS )
        menu_current = 0;
      menu_redraw_required = 1;
      break;
    case KEY_PREV:
      if ( menu_current == 0 )
        menu_current = MENU_ITEMS;
      menu_current--;
      menu_redraw_required = 1;
      break;
  }
}


void setup() {
  // rotate screen, if required
  // u8g.setRot180();
  
  uiSetup();                                // setup key detection and debounce algorithm
  menu_redraw_required = 1;     // force initial redraw
}

void loop() {  

  uiStep();                                     // check for key press
    
  if (  menu_redraw_required != 0 ) {
    u8g.firstPage();
    do  {
      drawMenu();
    } while( u8g.nextPage() );
    menu_redraw_required = 0;
  }

  updateMenu();                            // update menu bar
  
}
//////////////////////u8g2//////////////////////
#include "U8g2lib.h"

U8G2_ST7920_128X64_1_SW_SPI u8g2(U8G2_R2, 8, 9, 10 /* reset=*/ );


#define KEY_NONE 0
#define KEY_PREV 1
#define KEY_NEXT 2
#define KEY_SELECT 3
#define KEY_BACK 4

// DOGS102 shield configuration values
//uint8_t uiKeyPrev = 2;
//uint8_t uiKeyNext = 4;
//uint8_t uiKeySelect = 5;
//uint8_t uiKeyBack = 3;

// DOGM128-Shield   configuration values
// DOGXL60-Shield configuration values
uint8_t uiKeyPrev = 2;
uint8_t uiKeyNext = 3;
uint8_t uiKeySelect = 4;
uint8_t uiKeyBack = 5;

uint8_t uiKeyCodeFirst = KEY_NONE;
uint8_t uiKeyCodeSecond = KEY_NONE;
uint8_t uiKeyCode = KEY_NONE;
typedef u8g2_uint_t u8g_uint_t;

void uiSetup(void) {
  // configure input keys 
  
  pinMode(uiKeyPrev, INPUT_PULLUP);           // set pin to input with pullup
  pinMode(uiKeyNext, INPUT_PULLUP);           // set pin to input with pullup
  pinMode(uiKeySelect, INPUT_PULLUP);           // set pin to input with pullup
  pinMode(uiKeyBack, INPUT_PULLUP);           // set pin to input with pullup
}

void uiStep(void) {
  uiKeyCodeSecond = uiKeyCodeFirst;
  if ( digitalRead(uiKeyPrev) == LOW )
    uiKeyCodeFirst = KEY_PREV;
  else if ( digitalRead(uiKeyNext) == LOW )
    uiKeyCodeFirst = KEY_NEXT;
  else if ( digitalRead(uiKeySelect) == LOW )
    uiKeyCodeFirst = KEY_SELECT;
  else if ( digitalRead(uiKeyBack) == LOW )
    uiKeyCodeFirst = KEY_BACK;
  else 
    uiKeyCodeFirst = KEY_NONE;
  
  if ( uiKeyCodeSecond == uiKeyCodeFirst )
    uiKeyCode = uiKeyCodeFirst;
  else
    uiKeyCode = KEY_NONE;
}


#define MENU_ITEMS 4
const char *menu_strings[MENU_ITEMS] = { "First Line", "Second Item", "3333333", "abcdefg" };

uint8_t menu_current = 0;
uint8_t menu_redraw_required = 0;
uint8_t last_key_code = KEY_NONE;


void drawMenu(void) {
  u8g2_uint_t i, h;
  u8g2_uint_t w, d;

  u8g2.setFont(u8g2_font_t0_14_me);
  u8g2.setFontRefHeightText();
  u8g2.setFontPosTop();
  
  h = u8g2.getAscent()-u8g2.getDescent();
  w = u8g2.getWidth();
  for( i = 0; i < MENU_ITEMS; i++ ) {
    d = (w-u8g2.getStrWidth(menu_strings[i]))/2;
    u8g2.setFontMode(0);
    u8g2.setDrawColor(1);
    if ( i == menu_current ) {
      u8g2.drawBox(0, i*h+0.5, w, h);
      u8g2.setFontMode(0);
      u8g2.setDrawColor(1);
    }
    u8g2.drawStr(d, i*h, menu_strings[i]);
  }
}

void updateMenu(void) {
  if ( uiKeyCode != KEY_NONE && last_key_code == uiKeyCode ) {
    return;
  }
  last_key_code = uiKeyCode;
  
  switch ( uiKeyCode ) {
    case KEY_NEXT:
      menu_current++;
      if ( menu_current >= MENU_ITEMS )
        menu_current = 0;
      menu_redraw_required = 1;
      break;
    case KEY_PREV:
      if ( menu_current == 0 )
        menu_current = MENU_ITEMS;
      menu_current--;
      menu_redraw_required = 1;
      break;
  }
}


void setup() {
  // rotate screen, if required
  //u8g2.setRot180();
  u8g2.begin();
  uiSetup();                                // setup key detection and debounce algorithm
  menu_redraw_required = 1;     // force initial redraw
}

void loop() {  
  //u8g2.clearBuffer();
  uiStep();                                     // check for key press
    
  if (  menu_redraw_required != 0 ) {
    u8g2.firstPage();
    do  {
      drawMenu();
    } while( u8g2.nextPage() );
    menu_redraw_required = 0;
  }

  updateMenu();                            // update menu bar
  
}

**Comment by olikraus** [comment]
hmm... ok, looks like a wiring problem. I pushed the ST7920 very much to its limits with u8g2.
Try this:
locate u8x8_cad.c
Remove (or comment) lines 357 (https:https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_cad.c#L357//github.com/olikraus/u8g2/blob/master/csrc/u8x8_cad.c#L357)
to
371

**Comment by snapedumbledore** [comment]
I comment the lines  u8x8_cad.c(357-371),but the problem still exist. 
only the 'u8glib' works well.@olikraus

**Comment by snapedumbledore** [comment]
![img_20171019_200027](https://user-images.githubusercontent.com/29865320/31770853-4828a562-b50c-11e7-9872-fa9ed072411f.jpg)
still like this.

**Comment by olikraus** [comment]
Hmmm, You could also try to increase the delay which surrounds the code there.

**Comment by snapedumbledore** [comment]
I think there ara something wrong with my LCD .I use "u8glib",when I test "menu"example,it's OK.
but when I try others like"u8glogo"example ,failed.
![img_20171021_001359](https://user-images.githubusercontent.com/29865320/31831202-2fb38a6c-b5f5-11e7-9714-941024a6e4ae.jpg)

**Comment by olikraus** [comment]
It will probably not help if I say, that the ST7920 is the most unreliable display controller which is out there. Well, my suggestion is to make wires much shorter. Also consider soldering your connections to the display.

**Comment by snapedumbledore** [comment]
emmmm.I will try it ,thanks
